# Generated by Django 4.1.7 on 2023-03-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_izoh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izoh',
            old_name='user',
            new_name='ucer',
        ),
    ]
