# Generated by Django 4.1.7 on 2023-03-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_rename_user_izoh_ucer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izoh',
            old_name='ucer',
            new_name='user',
        ),
    ]
